### ISSUE TITLE
Issuing running the Demo with latest releases

### ISSUE THREAD

**Issue by awalter-bnl** [bluesky/bluesky-browser#29]
The demo doesn't run unless after pip installing blueksy-browser you then pip install blueksy --upgrade and pip install event-model --upgrade. We should resolve this.

**Comment by danielballan** [comment]
It's not obvious to me why it wouldn't work with old version of bluesky and event-model. What error do you get?

**Comment by awalter-bnl** [comment]
@danielballan below is the traceback  from me pip installing `bluesky-browser` after pulling from master. Then I show the traceback from trying to run the demo, the error in that traceback was resolved by doing `pip install bluesky --upgrade` and `pip install event-model --upgrade`.
```
alwalter@awalter01:~/NSLS-II/bluesky-browser$ pip install -e .
Obtaining file:///home/alwalter/NSLS-II/bluesky-browser
Requirement already satisfied: bluesky in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky-browser==0.post177+ged55b9c) (1.5.2)
Requirement already satisfied: event-model>=1.9.0a3 in /home/alwalter/NSLS-II/event-model (from bluesky-browser==0.post177+ged55b9c) (1.10.0.post8+gdcfdb49)
Requirement already satisfied: intake-bluesky>=0.1.0a5 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky-browser==0.post177+ged55b9c) (0.1.0a5)
Requirement already satisfied: jsonschema in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky-browser==0.post177+ged55b9c) (3.0.1)
Requirement already satisfied: matplotlib in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky-browser==0.post177+ged55b9c) (2.2.2)
Requirement already satisfied: ophyd in /home/alwalter/NSLS-II/ophyd (from bluesky-browser==0.post177+ged55b9c) (1.3.0.post395.dev0+gb743363)
Requirement already satisfied: pyqt5>=5.8 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky-browser==0.post177+ged55b9c) (5.12.1)
Requirement already satisfied: pyzmq in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky-browser==0.post177+ged55b9c) (16.0.4)
Requirement already satisfied: qtpy in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky-browser==0.post177+ged55b9c) (1.7.0)
Requirement already satisfied: suitcase-jsonl in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky-browser==0.post177+ged55b9c) (0.1.1)
Requirement already satisfied: tornado<5 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky-browser==0.post177+ged55b9c) (4.5.3)
Requirement already satisfied: traitlets in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky-browser==0.post177+ged55b9c) (4.3.2)
Requirement already satisfied: cycler in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky->bluesky-browser==0.post177+ged55b9c) (0.10.0)
Requirement already satisfied: toolz in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky->bluesky-browser==0.post177+ged55b9c) (0.9.0)
Requirement already satisfied: numpy in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky->bluesky-browser==0.post177+ged55b9c) (1.15.0)
Requirement already satisfied: historydict in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky->bluesky-browser==0.post177+ged55b9c) (1.2.3)
Requirement already satisfied: tqdm in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky->bluesky-browser==0.post177+ged55b9c) (4.24.0)
Requirement already satisfied: super-state-machine in /home/alwalter/miniconda3/lib/python3.6/site-packages (from bluesky->bluesky-browser==0.post177+ged55b9c) (2.0.2)
Requirement already satisfied: mongoquery in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (1.3.5)
Requirement already satisfied: pandas in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.23.4)
Requirement already satisfied: intake-xarray in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.3.0)
Requirement already satisfied: msgpack in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.5.6)
Requirement already satisfied: pymongo in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (3.8.0)
Requirement already satisfied: dask[bag] in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.20.0)
Requirement already satisfied: pyyaml in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (3.13)
Requirement already satisfied: intake<0.5.0 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.4.4)
Requirement already satisfied: requests in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (2.18.4)
Requirement already satisfied: xarray in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.11.1)
Requirement already satisfied: pyrsistent>=0.14.0 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from jsonschema->bluesky-browser==0.post177+ged55b9c) (0.14.5)
Requirement already satisfied: six>=1.11.0 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from jsonschema->bluesky-browser==0.post177+ged55b9c) (1.11.0)
Requirement already satisfied: attrs>=17.4.0 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from jsonschema->bluesky-browser==0.post177+ged55b9c) (18.2.0)
Requirement already satisfied: setuptools in /home/alwalter/miniconda3/lib/python3.6/site-packages (from jsonschema->bluesky-browser==0.post177+ged55b9c) (39.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from matplotlib->bluesky-browser==0.post177+ged55b9c) (2.3.0)
Requirement already satisfied: python-dateutil>=2.1 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from matplotlib->bluesky-browser==0.post177+ged55b9c) (2.7.5)
Requirement already satisfied: pytz in /home/alwalter/miniconda3/lib/python3.6/site-packages (from matplotlib->bluesky-browser==0.post177+ged55b9c) (2018.7)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from matplotlib->bluesky-browser==0.post177+ged55b9c) (1.0.1)
Requirement already satisfied: networkx>=2.0 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from ophyd->bluesky-browser==0.post177+ged55b9c) (2.3)
Requirement already satisfied: pyepics>=3.3.2 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from ophyd->bluesky-browser==0.post177+ged55b9c) (3.3.3)
Requirement already satisfied: PyQt5_sip<4.20,>=4.19.14 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from pyqt5>=5.8->bluesky-browser==0.post177+ged55b9c) (4.19.15)
Requirement already satisfied: suitcase-utils in /home/alwalter/miniconda3/lib/python3.6/site-packages (from suitcase-jsonl->bluesky-browser==0.post177+ged55b9c) (0.1.3)
Requirement already satisfied: ipython_genutils in /home/alwalter/miniconda3/lib/python3.6/site-packages (from traitlets->bluesky-browser==0.post177+ged55b9c) (0.2.0)
Requirement already satisfied: decorator in /home/alwalter/miniconda3/lib/python3.6/site-packages (from traitlets->bluesky-browser==0.post177+ged55b9c) (4.3.0)
Requirement already satisfied: netcdf4 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake-xarray->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (1.4.2)
Requirement already satisfied: zarr in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake-xarray->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (2.3.1)
Requirement already satisfied: partd>=0.3.8; extra == "bag" in /home/alwalter/miniconda3/lib/python3.6/site-packages (from dask[bag]->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.3.9)
Requirement already satisfied: cloudpickle>=0.2.1; extra == "bag" in /home/alwalter/miniconda3/lib/python3.6/site-packages (from dask[bag]->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.6.1)
Requirement already satisfied: jinja2 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake<0.5.0->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (2.10)
Requirement already satisfied: python-snappy in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake<0.5.0->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.5.4)
Requirement already satisfied: appdirs in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake<0.5.0->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (1.4.3)
Requirement already satisfied: msgpack-numpy in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake<0.5.0->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.4.4.2)
Requirement already satisfied: msgpack-python in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake<0.5.0->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.5.6)
Requirement already satisfied: holoviews in /home/alwalter/miniconda3/lib/python3.6/site-packages (from intake<0.5.0->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (1.12.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from requests->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from requests->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from requests->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from requests->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (2018.10.15)
Requirement already satisfied: cftime in /home/alwalter/miniconda3/lib/python3.6/site-packages (from netcdf4->intake-xarray->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (1.0.2.1)
Requirement already satisfied: numcodecs>=0.6.2 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from zarr->intake-xarray->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.6.3)
Requirement already satisfied: fasteners in /home/alwalter/miniconda3/lib/python3.6/site-packages (from zarr->intake-xarray->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.14.1)
Requirement already satisfied: asciitree in /home/alwalter/miniconda3/lib/python3.6/site-packages (from zarr->intake-xarray->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.3.3)
Requirement already satisfied: locket in /home/alwalter/miniconda3/lib/python3.6/site-packages (from partd>=0.3.8; extra == "bag"->dask[bag]->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.2.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from jinja2->intake<0.5.0->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (1.0)
Requirement already satisfied: pyviz-comms>=0.7.2 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from holoviews->intake<0.5.0->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (0.7.2)
Requirement already satisfied: param<2.0,>=1.8.0 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from holoviews->intake<0.5.0->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (1.9.0)
Requirement already satisfied: monotonic>=0.1 in /home/alwalter/miniconda3/lib/python3.6/site-packages (from fasteners->zarr->intake-xarray->intake-bluesky>=0.1.0a5->bluesky-browser==0.post177+ged55b9c) (1.5)
Installing collected packages: bluesky-browser
  Found existing installation: bluesky-browser 0.post177+ged55b9c
    Uninstalling bluesky-browser-0.post177+ged55b9c:
      Successfully uninstalled bluesky-browser-0.post177+ged55b9c
  Running setup.py develop for bluesky-browser
Successfully installed bluesky-browser
WARNING: You are using pip version 19.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

```
alwalter@awalter01:~/NSLS-II/bluesky-browser$ bluesky-browser --demo
Traceback (most recent call last):
  File "/home/alwalter/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/home/alwalter/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/alwalter/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (jsonschema 3.0.1 (/home/alwalter/miniconda3/lib/python3.6/site-packages), Requirement.parse('jsonschema<3'), {'bluesky'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alwalter/miniconda3/bin/bluesky-browser", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/alwalter/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/home/alwalter/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/home/alwalter/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/alwalter/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/alwalter/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/alwalter/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (jsonschema 3.0.1 (/home/alwalter/miniconda3/lib/python3.6/site-packages), Requirement.parse('jsonschema<3'), {'bluesky'})
```

**Comment by danielballan** [comment]
Can you reproduce that in a fresh environment?

**Comment by awalter-bnl** [comment]
I was not able to reproduce in a fresh enviroment, closing the issue as a possible issue with the enviroment used.
