### ISSUE TITLE
Issues at SMI

### ISSUE THREAD

**Issue by zhernenkov** [bluesky/bluesky-browser#53]
```py
(/opt/conda_envs/collection-2019-3.0.1-smi) xf12id@xf12id-ws1:~$ bluesky-browser smi-catalog.yml 
/opt/conda_envs/collection-2019-3.0.1-smi/lib/python3.7/site-packages/dask/config.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f.read()) or {}
/opt/conda_envs/collection-2019-3.0.1-smi/lib/python3.7/site-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-xf12id'
Traceback (most recent call last):
  File "/opt/conda_envs/collection-2019-3.0.1-smi/bin/bluesky-browser", line 12, in <module>
    sys.exit(main())
  File "/opt/conda_envs/collection-2019-3.0.1-smi/lib/python3.7/site-packages/bluesky_browser/main.py", line 128, in main
    app = build_app(args.catalog, zmq_address=args.zmq_address)
  File "/opt/conda_envs/collection-2019-3.0.1-smi/lib/python3.7/site-packages/bluesky_browser/main.py", line 141, in build_app
    menuBar=app.main_window.menuBar)
  File "/opt/conda_envs/collection-2019-3.0.1-smi/lib/python3.7/site-packages/bluesky_browser/main.py", line 36, in __init__
    catalog=catalog)
  File "/opt/conda_envs/collection-2019-3.0.1-smi/lib/python3.7/site-packages/bluesky_browser/search.py", line 87, in __init__
    self.set_selected_catalog(0)
  File "/opt/conda_envs/collection-2019-3.0.1-smi/lib/python3.7/site-packages/bluesky_browser/search.py", line 170, in set_selected_catalog
    self.selected_catalog = self.catalog[name]()
  File "/opt/conda_envs/collection-2019-3.0.1-smi/lib/python3.7/site-packages/intake/catalog/entry.py", line 78, in __call__
    s = self.get(**kwargs)
  File "/opt/conda_envs/collection-2019-3.0.1-smi/lib/python3.7/site-packages/intake/catalog/local.py", line 275, in get
    plugin, open_args = self._create_open_args(user_parameters)
  File "/opt/conda_envs/collection-2019-3.0.1-smi/lib/python3.7/site-packages/intake/catalog/local.py", line 256, in _create_open_args
    % self._driver)
ValueError: No plugins loaded for this entry: bluesky-mongo-normalized-catalog
A listing of installable plugins can be found at https://intake.readthedocs.io/en/latest/plugin-directory.html .
Exception ignored in: <function SearchState.__del__ at 0x7fd80f55a2f0>
Traceback (most recent call last):
  File "/opt/conda_envs/collection-2019-3.0.1-smi/lib/python3.7/site-packages/bluesky_browser/search.py", line 158, in __del__
AttributeError: 'SearchState' object has no attribute 'reload_thread'
(/opt/conda_envs/collection-2019-3.0.1-smi) xf12id@xf12id-ws1:~$ cat smi-catalog.yml 
sources:
  xyz:
    description: SMI catalog
    driver: bluesky-mongo-normalized-catalog
    container: catalog
    args:
      metadatastore_db: mongodb://xf12id-ca1:27017/datastore
      asset_registry_db: mongodb://xf12id-ca1:27017/filestore
    metadata:
      beamline: SMI
```

Version:
```
bluesky-browser           0.1.0a2                  py37_0    nsls-ii-2019C3.0.1
```

**Comment by danielballan** [comment]
This line

```
ValueError: No plugins loaded for this entry: bluesky-mongo-normalized-catalog
```

suggests that you don't have a new enough version of `databroker`. The required version is [marked here](https://github.com/bluesky/bluesky-browser/blob/84cfbeb4f1ef326640c3fa656467f575c582363b/requirements.txt#L3) but might not be correct in our conda packages at the moment. Can you show us

```
conda list | grep databroker
```

**Comment by mrakitin** [comment]
I did the ansible push earlier today to deploy `2019-3.0.1-smi` analysis and collection conda envs. Here is a version of `databroker` and `intake`:
```
databroker                0.13.3                     py_1    nsls-ii-2019C3.0.1
...
intake                    0.5.1                      py_0    defaults-2019C3.0
intake-bluesky            0.1.0a10                 py37_0    nsls-ii-2019C3.0.1
intake-xarray             0.3.0                      py_0    defaults-2019C3.0
```
